language: node_js
node_js: 10
dist: trusty

before_install:
  - npm install -g yarn # https://github.com/travis-ci/travis-ci/issues/9445#issuecomment-494864992

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: dist
    target_branch: gh-pages
    on:
      branch: master